### ISSUE TITLE
Expose physics params of ChatSCreenList

### ISSUE THREAD

**Issue by jinfagang** [themadmrj/chat_ui_kit#10]
Hi, in order to make users customable on list physics, I think its better add a params of physics.

**Comment by themadmrj** [comment]
> Hi, in order to make users customable on list physics, I think its better add a params of physics.

Make users customable? What do you mean?

**Comment by jinfagang** [comment]
physics is a param of List in flutter. You should expose it. etc, I want BouncingScrollPhysics() how to set it?

**Comment by themadmrj** [comment]
Yes I know what ScrollPhysics are haha :) I did not understand what you meant with "make users customable", that's all.
Feel free to submit a PR, otherwise I'll do it myself when the time comes, like I always do!

**Comment by jinfagang** [comment]
@themadmrj thank u! I just post this issue for your reference, I think this might be useful for someone who wants to custom their scroll physics.

**Comment by themadmrj** [comment]
Done in 1.2.0-nullsafety.0
