### ISSUE TITLE
ChatList add padding for custom

### ISSUE THREAD

**Issue by jinfagang** [themadmrj/chat_ui_kit#15]
ChatList currently can not add padding just like Listview does, I want add padding at ChatScreen page.

**Comment by themadmrj** [comment]
Added the parameter in the dev branch, you can switch to it if you don't want to wait for the next publish.

**Comment by jinfagang** [comment]
@themadmrj thank u. But I just notice that the padding I want is not every item's padding in listview. it's the padding from the whole listview so that on iOS I can make the listview scroll to the bottom still can make it above BottomBar so that last item can be seen.

**Comment by themadmrj** [comment]
> @themadmrj thank u. But I just notice that the padding I want is not every item's padding in listview. it's the padding from the whole listview so that on iOS I can make the listview scroll to the bottom still can make it above BottomBar so that last item can be seen.

If the last item is not visible, then you misdesigned your Widget. You're supposed to have your BottomBar inside of Scaffold and ChatsList or ChatMessagesList as your body. As such, it's impossible no to see the last item. What you're doing is a hack and will eventually lead to problems, as my experience tells me.

**Comment by jinfagang** [comment]
@themadmrj  Not sure do u have such an experience or not:

You have BottomNavigationBar which exactly part of scaffold, but you set it to translucent, so that you better make your listview **behind** the bar, then when you scroll, you will saw the content behind the blur bar, which looks a little bit nice.
But As the listview is fixed, extended to the right bottomest of screen, when you scrolled to last item, it will blind by bottombar.

I just want fix this problem, the only way I come up with is set a padding to the listview.

**Comment by themadmrj** [comment]
I think you'll have to find the solution by yourself. However, I'm not sure this is a good idea. I can see why you would make a transparent bottomNavBar with a picture undernearth but if there are icons or even redeable contents underneath, then it just seems like a bad idea.

**Comment by jinfagang** [comment]
@themadmrj That's why I want it have a padding so that it can be shown. However, on iOS, these listview are everywhere...
