### ISSUE TITLE
Logic error in assertion 

### ISSUE THREAD

**Issue by knaeckeKami** [themadmrj/chat_ui_kit#18]
on https://github.com/themadmrj/chat_ui_kit/blob/master/lib/src/widgets/core/messages_list.dart#L29, 

there is an assertion

```dart
assert(useCustomTile != null && builders.customTileBuilder != null,
            "You have to provide a customTileBuilder if you set useCustomTile"),
```

I think this is wrong. If you need to set both, you could make them required anyway.
I guess it should be "if useCustomTile is not null, then builders.customTileBuilder must also be not null".
which would be

```dart
assert(useCustomTile == null || builders.customTileBuilder != null,
            "You have to provide a customTileBuilder if you set useCustomTile")
```

**Comment by themadmrj** [comment]
Actually, it should be:

```
assert(useCustomTile != null && builders.customTileBuilder == null,
            "You have to provide a customTileBuilder if you set useCustomTile")
```

**Comment by themadmrj** [comment]
Edit: after further thought, you are 100% right, my bad!
