### ISSUE TITLE
Feature: add a ghost mode

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [themadmrj/chat_ui_kit#2]
Hi,
Im migrating my ui to your plugin 👌
One missing feature is ghost mode, having a chat in ghost mode delete all his messages after being seen..

Thx

**Comment by themadmrj** [comment]
> Im migrating my ui to your plugin 👌

Congrats! As of today it's by far the most complete chat kit, I was thinking of using [https://pub.dev/packages/dash_chat](url) but sadly they didn't deliver their v2.

> One missing feature is ghost mode, having a chat in ghost mode delete all his messages after being seen..
Can you elaborate? I didn't quite understand how it works.

**Comment by Abacaxi-Nelson** [comment]
Sure.
When creating a new chat, creator can choose a ghost mode (inspired by snapchat).
In that mode, when a message is posted by someone, and read by all other members: the message is deleted forever
.
Writing this, i realized, its not the responsibility of the lib to handle this feature: its not UI, its a business case :)

forget about this feature
