### ISSUE TITLE
The avatar enabled but the padding seems not perfectly aligned

### ISSUE THREAD

**Issue by luohao123** [themadmrj/chat_ui_kit#28]
Is this intended or miss aligned?

![image](https://user-images.githubusercontent.com/49749220/119219744-a151c800-bb19-11eb-8298-25378a6be776.png)

If it is intended, how do I make them all aligned?

**Comment by luohao123** [comment]
I tried the narrowed the avatar padding and size, I found the above message rows padding to the left doesn't changed at all. SO I think it might fixed inside, is there a way to make it aligned with avatar row?

**Comment by luohao123** [comment]
@themadmrj  Hi, sorry to at you again, Do u know how should I resolve this issue? many thanks if any suggestion can be provided.

**Comment by themadmrj** [comment]
I'll have more time a few days to check it out. Since I don't have this issue, I need to investigate deeper. Also, please provide the code you use to build the avatar.

**Comment by luohao123** [comment]
@themadmrj  For sure. If you have time, please help me take a look. Here is the code of 

```dart

 Widget _buildMessagesList() {
    IncomingMessageTileBuilders incomingBuilders = _isGroupChat
        ? IncomingMessageTileBuilders(
            bodyBuilder: (context, index, item, messagePosition) =>
                _buildMessageBody(context, index, item, messagePosition,
                    MessageFlow.incoming),
            avatarBuilder: (context, index, item, messagePosition) {
              final _chatMessage = item as ChatMessage;
              return Padding(
                  padding: EdgeInsets.only(right: 8),
                  child: ClipOval(
                      child: Image.asset(_chatMessage.author.avatar,
                          width: 32, height: 32, fit: BoxFit.cover)));
            })
        : IncomingMessageTileBuilders(
            bodyBuilder: (context, index, item, messagePosition) =>
                _buildMessageBody(context, index, item, messagePosition,
                    MessageFlow.incoming),
            // avatarBuilder: (context, index, item, messagePosition) {
            //   final _chatMessage = item as ChatMessage;
            //   return Padding(
            //       padding: EdgeInsets.only(right: 8),
            //       child: ClipOval(
            //           child: Image.network(_chatMessage.author.avatar,
            //               width: 24, height: 24, fit: BoxFit.cover)));
            // },
            titleBuilder: null);

    return Expanded(
        child: Padding(
            padding: EdgeInsets.only(left: 0, right: 0, bottom: 0),
            child: MessagesList(
                style: MessageStyle(
                    physics: BouncingScrollPhysics(),
                    padding:
                        EdgeInsets.only(left: 4, right: 4, top: 1, bottom: 1)),
                controller: _controller,
                scrollHandler: _handleScroll,
                appUserId: _currentUser.id,
                useCustomTile: (i, item, pos) {
                  final msg = item as ChatMessage;
                  return msg.isTypeEvent;
                },
                messagePosition: _messagePosition,
                builders: MessageTileBuilders(
                    customTileBuilder: _buildEventMessage,
                    customDateBuilder: _buildDate,
                    incomingMessageBuilders: incomingBuilders,
                    outgoingMessageBuilders: OutgoingMessageTileBuilders(
                        bodyBuilder: (context, index, item, messagePosition) =>
                            _buildMessageBody(context, index, item,
                                messagePosition, MessageFlow.outgoing))))));
  }

```

the **comment out** part is code I added, simply using almost same code as example in your folder. I just enabled avatar not only in group but also o2o chat.

**Comment by themadmrj** [comment]
This is well documented, please read the docs...
From `message_style.dart`

```
  /// Constrained width for the avatar, when displayed
  /// if an avatarBuilder is supplied but no avatar is built due to positioning,
  /// [avatarWidth] is also used to build an empty container to align all messages
  final double avatarWidth;
```

This means that the total width reserved for your avatar is `avatarWidth`. Therefore, since your avatar has a size of (32,32), you'll need a 16px padding with your avatar to make it aligned. If you want to reduce the padding, the you just have to pass a custom `avatarWidth`.

**Comment by luohao123** [comment]
@themadmrj  Thank u, forgive me If I made you missundertood me.

**You are right set avatarWidth bigger**, but my question is, if I set avatarWidth bigger, the padding whole incoming messages looks to much right. In other words, I want the padding between bubble and avatar smaller, as well as the whole incoming messages to the leftest of screen.

AFAIK, current situation is:

- if I set avatarWidth aligned to incoming messages, it looks too much right;
- if I set avatarWidth smaller, the last incoming messages looks normal, but not rest of them.

I can fix the avatarWidth to make them aligned, but looks too much right. On the other words, how to make the upper incoming messages padding to left, can be smaller? (you can not force users use a fixed avatarWidth  otherwise it will miss-aligned right?)

**Comment by themadmrj** [comment]
That's because the outer padding of each tile (message), is determined in `MessageStyle`.

```
/// The outer padding of each tile
final EdgeInsets padding;
```

Thus, you if you want an avatar with 8px padding left and right, you need to set MessageStyle.padding to 8px and give an additionnal padding right to your avatar of 8px, and finally make sure avatar width + avatar padding = avatarPadding.
This could indeed be computed automatically, but atm I don't have the time to refactor it, so you'll have to use the settings planned out for it.
