### ISSUE TITLE
[feature] Add the padding to ImplicitlyAnimatedList

### ISSUE THREAD

**Issue by jinfagang** [themadmrj/chat_ui_kit#30]
https://github.com/bnxm/implicitly_animated_reorderable_list/issues/77#issuecomment-853332816

After a long discussion with this lib author, it seems can set the padding value to ImplicitlyAnimatedList.
My proposal is can you consider expose this params out so that users can choose to set it or not? thanks.

**Comment by themadmrj** [comment]
Sure I can. But have you tested it?

**Comment by jinfagang** [comment]
@themadmrj I haven't Sir. Can u indicates me where put the params is OK, let me test it on my side first since only my APP have this weired usage.

**Comment by themadmrj** [comment]
You don't need a change in the library. Just change the code in your cache to test it. If it solves your problem, I'll make the change in the lib.

**Comment by jinfagang** [comment]
@themadmrj Don't understand. I mean which class I need change to the chatui....

**Comment by themadmrj** [comment]
I'm just saying I'm waiting for you to test the solution to check whether it works, before I change the library...
