### ISSUE TITLE
the example is not null safety

### ISSUE THREAD

**Issue by sleepreading** [themadmrj/chat_ui_kit#33]

**Comment by themadmrj** [comment]
Which part?

**Comment by themadmrj** [comment]
Don't you just love self solving problems? xD

**Comment by sleepreading** [comment]
Sorry about that. But it's really everwhere, for example:
![image](https://user-images.githubusercontent.com/7484631/125554791-af47d449-4ed3-4594-a5c4-bce2270f9533.png)

And we have more problems here: Template T can't implicitly cast to base class or Object:
![image](https://user-images.githubusercontent.com/7484631/125555301-43485c03-24ee-40fc-89b3-465dac78902b.png)

**Comment by sleepreading** [comment]
**sdk environment**:
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git  
Framework • revision f4abaa0735 (12 days ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

**pubspec.yaml**:
```
environment:
  sdk: ">=2.12.3"
```

**Comment by themadmrj** [comment]
Indeed, after updating the sdk dep, all the non null safety got highlighted. Thanks for pointing that out, I'll release an update asap!
