### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by dannycortesv** [themadmrj/chat_ui_kit#37]
Example is not the same as the screenshots, right? Is there a way to record audio/video or upload files?

**Comment by themadmrj** [comment]
The screenshots are from a production app of mine called `Zappr`. You can download and check it out.

> Is there a way to record audio/video or upload files?

I have yet to see a UI kit that provides this. What you get is easy `display`, not content `creation`. Here a few tips to get you started:

Record an audio:
```
import 'package:record/record.dart';
Record.start();
Record.stop();
```

Record a video:
Internal camera: https://pub.dev/packages/camera
Using the device's camera app: https://pub.dev/packages/image_picker

Upload files:
Basic http request to upload data. I use https://pub.dev/packages/retrofit to abstract the process.

Good luck.

**Comment by dannycortesv** [comment]
@themadmrj thanks mate!
