### ISSUE TITLE
Avatar from network

### ISSUE THREAD

**Issue by jc324** [themadmrj/chat_ui_kit#39]
Hi,

Thanks for open sourcing this kit. I was wondering if it supports loading images from a network. I couldn't get that to work. Is there some widget that could be extended or something? Thanks.

**Comment by themadmrj** [comment]
Instead of using `Image.asset`, you just can just use `Image.network`. Or you can use any library you want. I use [cached_network_image](https://pub.dev/packages/cached_network_image)

**Comment by jc324** [comment]
Does the kit provide an API to change that, or do I have to fork this kit?

**Comment by themadmrj** [comment]
Why would you want to fork for this? You can do it exactly like it is done in the example application. Copy paste the code from `chat_message_image.dart`, change to use any library or loader that you like and use that Widget just like shown in `chat_screen.dart`.

**Comment by jc324** [comment]
Is it the `groupAvatarBuilder` property? BTW, I'm not willing to fork just for the this, only if there was no other way.

**Comment by jc324** [comment]
I figured it out. Thanks so much.
