### ISSUE TITLE
lastMessage must be non null

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [themadmrj/chat_ui_kit#4]
Hi,
From your example, each ```ChatWithMembers``` must have a ``` lastMessage ``` not null. 
But, when creating a new instance of ```ChatWithMembers```, ``` lastMessage ``` is necessarily null.

Error is thrown here : [https://github.com/themadmrj/chat_ui_kit/blob/3d03ae5de83906d01a4cd78bff2758be2397a0c2/lib/src/widgets/core/chats_list_tile.dart#L162](https://github.com/themadmrj/chat_ui_kit/blob/3d03ae5de83906d01a4cd78bff2758be2397a0c2/lib/src/widgets/core/chats_list_tile.dart#L162)

How handle a chat without messages ?

Nelson,

**Comment by themadmrj** [comment]
What's the point of displaying an empty chat? That's the question I asked myself when I wrote that line.
If there are valid reasons, I can make the change.

**Comment by Abacaxi-Nelson** [comment]
I have a use case (We call it ghost mode), where i delete all message on behalf of members, but keep their conversation. 

> What's the point of displaying an empty chat? That's the question I asked myself when I wrote that line.
> If there are valid reasons, I can make the change.
You are right, but it can happen before first message come (All member get their chat list updated, on chat creation, not when first message is fired).

I can create a fake first message, but im not sure its good..

**Comment by Abacaxi-Nelson** [comment]
BTW, i can pass my own builder, so i can make my own widget :)
Thanks,

**Comment by themadmrj** [comment]
Changed in 1.1.3
