### ISSUE TITLE
[Feature] Mark Message as 

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [themadmrj/chat_ui_kit#5]
Hi
Your library is so great ! thank you so much to share it.

**Use case:** 

1. User want to reply to a message
2. User want to modify his own message

For use case 2, im using existing API on controller [https://github.com/themadmrj/chat_ui_kit/blob/3d03ae5de83906d01a4cd78bff2758be2397a0c2/lib/src/utils/controllers.dart#L100](https://github.com/themadmrj/chat_ui_kit/blob/3d03ae5de83906d01a4cd78bff2758be2397a0c2/lib/src/utils/controllers.dart#L100)

**The process is : Mark a message > Update the UI > When a message is send > Detect if a message is marked > Update database according to**

It enable me, to update the UI (show the old message on top of the submit form).
When user is done, i ```unselect```

```select```is a great way to select multiple messages once, and make something on them.
But we need also, a ```markAsModify```, ```markAsReply``` to make the controller more complete.

```dart
void mark(T item, String family) {
    _markItems[family] = item;
    notifyListeners();
    _controller.sink.add(****);
  } 
```

**Comment by themadmrj** [comment]
Since it doesn't seem to conflict with already existing features/code, feel free to make a pull request and I'll merge it asap :)

**Comment by jinfagang** [comment]
@themadmrj  Does this lib stores messages data to database ?

**Comment by themadmrj** [comment]
> @themadmrj Does this lib stores messages data to database ?

No, it is a UI kit, so the dev has to implement any database operation. It would be a pain to do, since every project requires a different Chat/Message model.

**Comment by jinfagang** [comment]
@themadmrj  Yeah yeah, exactly
