### ISSUE TITLE
Bug: updateById does not use parameter value

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [themadmrj/chat_ui_kit#6]
Hi,

[https://github.com/themadmrj/chat_ui_kit/blob/3d03ae5de83906d01a4cd78bff2758be2397a0c2/lib/src/utils/controllers.dart#L182](https://github.com/themadmrj/chat_ui_kit/blob/3d03ae5de83906d01a4cd78bff2758be2397a0c2/lib/src/utils/controllers.dart#L182)

Item here is took from _items, and reinsert few lines after. Modified value pass as parameter is not used.

Can fix it on my futur PR: [https://github.com/themadmrj/chat_ui_kit/issues/5#issue-792776713](https://github.com/themadmrj/chat_ui_kit/issues/5#issue-792776713) if you want.

**Comment by themadmrj** [comment]
Good find, thnx a lot! It's fine I'll change it.
