### ISSUE TITLE
Bug: Pass style down IncomingMessage

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [themadmrj/chat_ui_kit#7]
In [https://github.com/themadmrj/chat_ui_kit/blob/e99d4ed5ca490b5dbc978fecff6009ff04209700/lib/src/widgets/core/messages_list_tile.dart#L124](https://github.com/themadmrj/chat_ui_kit/blob/e99d4ed5ca490b5dbc978fecff6009ff04209700/lib/src/widgets/core/messages_list_tile.dart#L124)

Pass also the style property:

```dart
IncomingMessage(
                // Bug Here
                style: style,
                item: item,
                index: index,
                messagePosition: messagePosition,
                builders: builders.incomingMessageBuilders));
```

**Comment by themadmrj** [comment]
Done in next update.
